### ISSUE TITLE
Selection and dragging prevents slider movement.

### ISSUE THREAD

**Issue by ghost** [Polymer/paper-slider#17]
If I drag the knob quite a bit beyond the sliders limits and release the mouse-button, certain elements of the `paper-slider` get selected which then will be dragged instead of the knob on the next slider movement.

I did not check other browsers, within Chrome I fixed the problem by adding the lines below to `paper-slider.css`

``` css
.slider-markers, #sliderBar, #sliderKnob {
  -webkit-user-select: none;
  -webkit-user-drag: none;
}
```
