### ISSUE TITLE
paper-slider incompatibility with Bootstrap

### ISSUE THREAD

**Issue by GGG-KILLER** [Polymer/paper-slider#50]
Since bootstrap uses the css

``` css
* {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
*:before,
*:after {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
```

it makes the paper slider not show up, and only the slider bob shows up(it can be fixed by commenting those lines, as I did, but I'm not sure if its really needed by Bootstrap).
